version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: marketplace-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: marketplace
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ${PWD}/.docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

